name: openreception_client
description: Receptionist browser-based console for OpenReception project.
version: 0.0.1
dependencies:
  browser: any
  event_bus: <0.3.0
  intl: any
  js: any
  logging: any
  meta: any
  okeyee: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenReceptionFramework.git
    version: '>= 0.0.17'
