name: ReceptionistClientFlex
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenreceptionFramework.git
