name: ORC
version: 0.5.0
description: A receptionist web-app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  dart_to_js_script_rewriter: any
  intl: any
  logging: any
  markdown: any
  okeyee: any
  openreception.framework:
    path: ../framework
    version: '>=0.0.30'
transformers:
- dart_to_js_script_rewriter
