name: ORC
version: 0.5.0
description: A receptionist web-app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  dart_to_js_script_rewriter: any
  intl: any
  logging: any
  markdown: any
  okeyee: any
  openreception_framework:
    version: '>=0.0.25+14'
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenreceptionFramework.git
transformers:
- dart_to_js_script_rewriter
