name: ReceptionistClient
version: 0.5.0
description: A receptionist web-app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  intl: any
  logging: any
  markdown: any
  okeyee: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenreceptionFramework.git
    version: '>=0.0.22+32'
