#define PJ_SCANNER_USE_BITWISE	0
#undef PJ_OS_HAS_CHECK_STACK
#define PJ_OS_HAS_CHECK_STACK	0
#define PJ_LOG_MAX_LEVEL		3
#define PJ_ENABLE_EXTRA_CHECK	0
#define PJ_IOQUEUE_MAX_HANDLES	1024
#define PJSIP_MAX_TSX_COUNT		((640*1024)-1)
#define PJSIP_MAX_DIALOG_COUNT	((640*1024)-1)
#define PJSIP_UDP_SO_SNDBUF_SIZE	(24*1024*1024)
#define PJSIP_UDP_SO_RCVBUF_SIZE	(24*1024*1024)
#define PJ_DEBUG			0
#define PJSIP_SAFE_MODULE		0
#define PJ_HAS_STRICMP_ALNUM		0
#define PJ_HASH_USE_OWN_TOLOWER	1
#define PJSIP_UNESCAPE_IN_PLACE	1

#define PJSUA_MAX_CALLS			512
