name: openreception.server
version: 0.2.0+rc-1
description: Server stack for the OpenReception application.
dependencies:
  args: any
  crypto: any
  emailer:
    git:
      ref: master
      url: https://github.com/Bitstackers/emailer.git
  esl:
    git:
      ref: master
      url: https://github.com/rostgaard/libesl-dart.git
    version: '>0.0.15 <0.1.0'
  http: any
  intl: any
  logging: any
  oauth2: <1.0.0
  openreception.framework:
    path: ../framework
    version: '>=0.0.30'
  route: any
  web_socket_channel: any
  shelf: any
  shelf_auth: any
  shelf_cors: any
  shelf_route: any
  shelf_web_socket: '>= 0.1.0 <0.2.0'
