name: ServerStack
version: 0.1.10+beta
description: Server stack for the OpenReception application.
dependencies:
  args: any
  crypto: any
  emailer:
    git:
      ref: master
      url: https://github.com/Bitstackers/emailer.git
  esl:
    git:
      ref: master
      url: https://github.com/rostgaard/libesl-dart.git
    version: '>0.0.15 <0.1.0'
  http: any
  intl: any
  libdialplan:
    git:
      ref: master
      url: https://github.com/AdaHeads/libdialplan.git
  logging: any
  oauth2: '<1.0.0'
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
    version: '>=0.0.25'
  path: any
  postgresql: '>= 0.3.0 <4.0.0'
  route: any
  shelf: any
  shelf_cors: any
  shelf_route: any
