name: ServerStack
description: Server stack for the OpenReception application.
version: 0.1.1+beta
dependencies:
  args: any
  crypto: any
  intl: any
  http: any
  oauth2: any
  openreception_framework:
    version: ">= 0.0.21+0"
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  route: any
  postgresql: '>= 0.3.0 <4.0.0'
  libdialplan:
    git:
      ref: master
      url: https://github.com/AdaHeads/libdialplan.git
  esl:
    git:
      ref: master
      url: https://github.com/rostgaard/libesl-dart.git
  logging: any
