name: openreception_servers
version: 0.1.15+beta
description: Server stack for the OpenReception application.
dependencies:
  args: any
  crypto: any
  emailer:
    git:
      ref: master
      url: https://github.com/Bitstackers/emailer.git
  esl:
    git:
      ref: master
      url: https://github.com/rostgaard/libesl-dart.git
    version: '>0.0.15 <0.1.0'
  http: any
  intl: any
  logging: any
  oauth2: <1.0.0
  openreception_framework:
    git:
       ref: master
       url: https://github.com/rostgaard/OpenReceptionFramework.git
    version: '>=0.0.26'
  route: any
  shelf: any
  shelf_auth: any
  shelf_cors: any
  shelf_route: any
  shelf_web_socket: '>= 0.1.0 <0.2.0'
