part of or_test_fw;

abstract class Randomizer {

  static final List<String> events =
      ['Milk purchase',
       'Meeting with ${randomChoice(contacts)}',
       'All work and no play',
       'Roller coaster inspection',
       'Prepare world domination'];

  static final List<String> contacts =
      ['Alexandra Kongstad Pedersen',
       'Anne And',
       'Gardenia Hø',
       'Hans Hansen',
       'Peter Petersen',
       'Tom Thomsen',
       'Petra Petrea',
       'Gunner Gunnersen',
       'Ole Olesen',
       'Helga Helgason',
       'Martinus Martinussen',
       'Bob Børgesen',
       'Charlie Carstensen',
       'Alice Arnesen',
       'Charlie Carstensen',
       'Bob Børgesen',
       'Bente Bogfinke',
       'Carla Cikade',
       'Dorthe Dådyr',
       'Eva Egern',
       'Frode Flyvemyre',
       'Gerda Ged',
       'Hans Havodder',
       'Ida Isfugl',
       'Jan Jordbi',
       'Karsten Klokkefrø',
       'Lars Latterfrø',
       'Maren Muldvarp',
       'Nille Natugle',
       'Ole Odder',
       'Petra Pindsvin',
       'Ronald Rødspætte',
       'Sune Syvsover',
       'Tulla Trane',
       'Ulla Undulat',
       'Verner Vaskebjørn',
       'Allan Abe',
       'Børge Bæver',
       'Carlo Connemara',
       'Dorian Dompap',
       'Eskild Edderfugl',
       'Frank Fritte',
       'Gunner Grævling',
       'Heidi Husmus',
       'Lars Latterfrø',
       'Frank Fritte',
       'Eskild Edderfugl',
       'Helga Helgason',
       'Martinus Martinussen',
       'Anja Hansen',
       'Astrid Bang',
       'Birgit Blomquist',
       'Janne Winther Andreasen',
       'Knud Jønsson',
       'Morten Smidt-Holm',
       'Naja Duelund',
       'Oda Olsen',
       'Gert Keld',
       'Perry Næbdyr',
       'Palle Letkniv',
       'Anders Sand',
       'Rie Gid S.Todder',
       'Kvak S. Alver',
       'Sigmund Sivsko'];

  static final List<String> positions =
      ['Forskningsleder/seniorforsker',
        'Forsker',
        'Administrationschef',
        'Kreditorbogholder',
        'Forskningsleder/seniorforsker',
        'Direktør',
        'Seniorforsker',
        'Sekretær/debitorbogholder',
        'Senior Superman',
        'Nattevagt',
        'Overlæge',
        'Underlæge',
        'Bussemandsskræmmer',
        'Spøgelsesjæger',
        'Grønthøster',
        'Blåhvalsjæger',
        'Myresluger',
        'Underdirektør',
        'Potteskjuler',
        'Hegnbestiger',
        'Glaspuster',
        'Næsepudser',
        'Kummebejser',
        'Skærmtrold',
        'Møntvender',
        'Bagvender',
        'Sivskofletter',
        'Ordkløver',
        'Tingfinder',
        'Sodavandsbæller',
        'Dynevender',
        'Endevender',
        'Vendekåbe',
        'Stoledanser',
        'Frisbeehenter',
        'IKEA-skab-samler',
        'Ringbind',
        'Stalker',
        'Blotter',
        'F5-Trykker',
        'Lusepuster',
        'Lyseslukker',
        'Sneglekoger',
        'Frølårsklipper',
        'Dåseåbner',
        'Hvidløgspresser',
        'Pruttens ejermand'];

  static final List<String> companyNames = [
        'Kødbollen A/S',
        'Blomme\'s Gartneri',
        'Hummerspecialisten ApS',
        'Gnaske-Grønt ApS',
        'Firmanavn_der_fortæller_om_samtlige_produkter_hos_os A/S',
        'BulgurKompaniget A/S',
        'Andefødder Aps',
        'Spirevippen I/S',
        'Petersen\'s Globale Kobberudvinding',
        'PingPong ApS',
        'Kasper\'s Køkken A/S',
        'Den Varme Radiator ApS',
        'KludeCentralen ApS',
        'MobileAdvolaterne A/S',
        'Bogforlaget A/S',
        'Revisor Søren ApS',
        'Den Varme Radiator ApS',
        'KludeCentralen ApS',
        'MobileAdvolaterne A/S',
        'Bogforlaget A/S',
        'Revisor Søren ApS',
        'Kalle\'s Dyrefoder ApS',
        'Fantasibureauet A/S',
        'Fem Flade fisk I/S',
        'Advokatkontoret',
        'Gave-Ideer ApS',
        'Det Tredie Firmanavn I/S',
        'Kraniosakralklinikken ApS',
        'Hvalbøffer A/S',
        'De gode ideer ApS',
        'Super-supporten A/S',
        'Doozerne A/S',
        'Sublim Forskning A/S',
        'Hårtotten ApS',
        'Alt til katten A/S',
        'Sjov og Spas',
        'Humørbomben K/S',
        'Kurts kartoffelskrællerservice',
        'Det absolutte nulpunkt',
        'Den hellige ko-kebab',
        'Peters pottemageri',
        'Reklamegas Aps',
        'Lenes lækre lune lagner I/S',
        'Grine-Gerts anti-depressiver',
        'Kasse-kompaniet',
        'Hårstiverne'];

  static final userNames = [
        'Bob Børgesen',
        'Alice Arnesen',
        'Charlie Carstensen',
        'Dorthe Didriksen',
        'Erik Einersen',
        'Frede Frandsen',
        'Gurli Gunnersen',
        'Heidi Hermansen',
        'Ida Iversen',
        'Julius Jensen',
        'Rasmine Rapmund',
        'Signe Snaksom',
        'Sanne Sludrechartol',
        'Miranda Migrene',
        'Tage Fortalsom',
        'Mogens Morgenånde',
        'Bengt Blidrøst',
        'Svend Skrap',
        'Børge Bralder',
        'Buller Bredmund',
        'Ove Overlæbe',
        'Misse Mundvand'];

  static String randomEvent() => randomChoice(events);

  static dynamic randomChoice (List pool) {
    if(pool.isEmpty) {
      throw new ArgumentError('Cannot find a random value in an empty list');
    }

    int seed = new DateTime.now().millisecondsSinceEpoch;
    int index = new Random(seed).nextInt(pool.length);

    return  pool[index];
  }
}