name: MessageServer
description: A sample command-line application
dependencies:
  OpenReceptionFramework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  mailer: any
  path: any
  postgresql: any
  route: any
