name: MessageServer
description: A sample command-line application
dependencies:
  args: any
  mailer: any
  openreception_framework:
    #git:
    #  ref: converging_model
    #  url: https://github.com/AdaHeads/OpenReceptionFramework.git
    path: /home/krc/Projects/OpenReceptionFramework
  path: any
  postgresql: any
  route: any
