name: MessageServer
description: A sample command-line application
dependencies:
  args: any
  mailer: any
  openreception_framework:
     version: ">= 0.0.13+0"
     git:
       ref: master
       url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
