name: MessageServer
description: A sample command-line application
dependencies:
  args: any
  mailer: any
  openreception_framework:
    path: "/home/krc/Projects/OpenReceptionFramework"
    version: ">= 0.0.15+2"
  path: any
  postgresql: any
  route: any
