name: MessageServer
description: Message (like in email-message, not MPI) management server for OpenReception system.
version: 0.0.1
dependencies:
  args: any
  http: any
  intl: any
  postgresql: '>= 0.3.0'
  mailer: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenReceptionFramework.git
    version: '>= 0.0.17+1'
  path: any
  route: any
