name: CallFlowControl
version: 0.1.1
author: Kim Rostgaard Christensen
description: Call-Flow-Control server.
dependencies:
  args: any
  esl:
    git: https://github.com/rostgaard/libesl-dart.git
  openreception_framework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  route: any
