name: 'openreception.client_app_server'
version: 0.0.1
description: Simple web server for serving the web-client supporting pushstate.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_static: any
  shelf_route: any
