name: ContactServer
description: A sample command-line application
dependencies:
  args: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
