name: CallFlowControlWrapper
description: Simple HTTP wrapper around the Call-Flow-Control socket interface.
dependencies:
  OpenReceptionFramework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  path: any
  route: any
