name: openreception_framework
version: 0.0.15+6
author: BitStackers
description: 
  A utility package for the OpenReception application that provides data model
  service and storage layer.
dependencies:
  http: any
  junitconfiguration: '>=1.0.0 <2.0.0'
  logging: any
  postgresql: '>= 0.3.0'
  route: any
  syslog:
    git: https://github.com/PedersenThomas/syslog.git
  unittest: any
