name: openreception_framework
version: 0.0.15
author: BitStack K/S
description: A utility package for the OpenReception application.
dependencies:
  http: any
  junitconfiguration: '>=1.0.0 <2.0.0'
  logging: any
  postgresql: '>= 0.3.0'
  route: any
  syslog:
    git: https://github.com/PedersenThomas/syslog.git
  unittest: any
