name: OpenReceptionFramework
version: 0.0.10+2
description: A utility package for the OpenReception application.
dependencies:
  http: any
  postgresql: any
  route: any
  syslog:
    git: https://github.com/PedersenThomas/syslog.git
auther: AdaHeads K/S
