name: openreception_framework
version: 0.0.27+16
author: BitStackers
description: A utility package for the OpenReception application that provides data model service and storage layer.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: any
dev_dependencies:
  http: any
  junitconfiguration: '>=1.0.0 <2.0.0'
  logging: any
  postgresql: '>= 0.3.0 <4.0.0'
  route: any
  unittest: '>= 0.11.5 < 0.12.0'
  xml: any
