name: OpenReceptionFramework
version: 0.0.5
description: A utility package for AdaHeads K/S
dependencies:
  http: any
  postgresql: any
  route: any
  syslog:
    git: https://github.com/PedersenThomas/syslog.git
auther: AdaHeads K/S
