name: MiscServer
description: Configuration management server.
dependencies:
  openreception_framework:
    git:
      ref: converging_model
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  path: any
  postgresql: any
  route: any
