name: MiscServer
description: Configuration management server.
dependencies:
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  args: any
  path: any
  postgresql: any
  route: any
