name: openreception_acceptance_tests
version: 0.1.1
description: OpenReception Acceptance tests
dependencies:
  http: any
  junitconfiguration: any
  logging: any
  openreception_framework:
    #git: https://github.com/Bitstackers/OpenReceptionFramework.git
    path: /home/krc/Projects/OpenReceptionFramework
  phonio:
    path: /home/krc/Projects/Phonio
    #git: https://github.com/Bitstackers/Phonio.git
  route: any
  unittest: any
