name: openreception_acceptance_tests
description: OpenReception Acceptance tests
dependencies:
  phonio:
#    git: https://github.com/Bitstackers/Phonio.git
    path: "/home/krc/Projects/Phonio"
  logging: any
  openreception_framework:
    git: https://github.com/Bitstackers/OpenReceptionFramework.git
  unittest: any
 