name: ort
version: 0.3.0
description: OpenReception Acceptance and integration tests
dependencies:
  http: any
  logging: any
  esl:
    git:
      ref: devel
      url: https://github.com/rostgaard/libesl-dart.git
  orf:
    path: ../framework
    version: '>=0.0.30'
  openreception.client_app_server:
    path: ../tools/client_app_server
  phonio:
    git: https://github.com/Bitstackers/Phonio.git
  route: any
  shelf: '>=0.6.0 <0.7.0'
  shelf_static: any
  shelf_cors: any
  shelf_route: any
dev_dependencies:
  test: any
