name: openreception_acceptance_tests
version: 0.1.9
description: OpenReception Acceptance and integration tests
dependencies:
  http: any
  junitconfiguration: any
  logging: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
    version: '>0.0.24+6'
  phonio:
    git: https://github.com/Bitstackers/Phonio.git
  route: any
  shelf: any
  shelf_cors: any
  shelf_route: any
  postgresql: any
dev_dependencies:
  unittest: '>=0.11.5 <0.12.0'
