
name: openreception_acceptance_tests
version: 0.1.8
description: OpenReception Acceptance and integration tests
dependencies:
  http: any
  junitconfiguration: any
  logging: any
  openreception_framework:
    version: ">= 0.0.21+0"
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  phonio:
    git: https://github.com/Bitstackers/Phonio.git
  route: any
  unittest: any
