name: NotificationServer
description: Simple notification server.
dependencies:
  args: any
  openreception_framework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  route: any
