name: NotificationServer
description: Simple notification server.
dependencies:
  args: any
  logging: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  intl: any
  route: any
  http: any
  syslog:
    git: https://github.com/PedersenThomas/syslog.git

