name: NotificationServer
description: Simple notification server.
dependencies:
  args: any
  logging: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  route: any
