name: UserServer
description: Simple user server.
dependencies:
  args: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  route: any
