name: UserServer
description: Simple user server.
dependencies:
  args: any
  openreception_framework:
    git:
      ref: converging_model
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  route: any
