name: AuthServer
description: A sample command-line application
dependencies:
  openreception_framework:
    git:
      ref: converging_model
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  crypto: any
  http: any
  oauth2: any
  path: any
  route: any
