name: AuthServer
description: A sample command-line application
dependencies:
  args: any
  crypto: any
  http: any
  oauth2: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/BitStackers/OpenReceptionFramework.git
  path: any
  route: any
