name: AuthServer
description: A sample command-line application
dependencies:
  OpenReceptionFramework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  crypto: any
  http: any
  oauth2: any
  path: any
  route: any
