name: management_tool
version: 0.0.1
description:
author: BitStackers
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^0.1.0
  event_bus: any
  intl: any
  logging: any
  okeyee: any
  route_hierarchical: any
  stream_channel: any
  openreception_framework:
    git:
      ref: master
      url: https://github.com/rostgaard/OpenreceptionFramework.git
    version: '>=0.0.30'
transformers:
- dart_to_js_script_rewriter
