name: management_tool
version: 0.0.1
author: Your Name <email@example.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^0.1.0
  event_bus: any
  intl: any
  logging: any
  okeyee: any
  openreception_framework:
    path: ../framework
  route_hierarchical: any
  stream_channel: any
transformers:
- dart_to_js_script_rewriter
