name: management_tool
version: 0.1.0
description:
author: BitStackers
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  route_hierarchical: any
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^0.1.0
  intl: any
  logging: any
  okeyee: any
  random_string: any
  route_hierarchical: any
  stream_channel: any
  openreception.framework:
    path: ../framework
    version: '>=0.0.30'
transformers:
- dart_to_js_script_rewriter
