name: ManagementClient
description: A sample web application
dependencies:
  browser: any
  event_bus: any
  html5_dnd: any
  intl: any
  libdialplan:
    git:
      ref: master
      url: https://github.com/AdaHeads/libdialplan.git
  openreception_framework:
    git:
      ref: master
      url: https://github.com/Bitstackers/OpenReceptionFramework.git
  okeyee: any
