name: ManagementClient
description: A sample web application
dependencies:
  browser: any
  event_bus: any
  html5_dnd: any
  okeyee: any
  libdialplan:
    git: 
      url: git@github.com:AdaHeads/libdialplan.git
      ref: master
