name: ManagementClient
description: A sample web application
dependencies:
  browser: any
  event_bus: any
  html5_dnd: any
  libdialplan:
    git:
      ref: namedgroup
      url: git@github.com:PedersenThomas/libdialplan.git
  okeyee: any
