library id;

const String CONTEXT_HOME       = 'contexthome';
const String CONTEXT_MESSAGES   = 'contextmessages';
const String CONTEXT_LOG        = 'contextlog';
const String CONTEXT_STATISTICS = 'contextstatistics';
const String CONTEXT_PHONE      = 'contextphone';
const String CONTEXT_VOICEMAILS = 'contextvoicemails';

const String COMPANY_ADDRESSES           = 'companyaddresses';
const String COMPANY_ALTERNATENAMES      = 'companyalternatenames';
const String COMPANY_BANKING_INFORMATION = 'companybankinginformation';
const String COMPANY_CUSTOMERTYPE        = 'companycustomertype';
const String COMPANY_EMAIL_ADDRESSES     = 'companyemailaddresses';
const String COMPANY_EVENTS              = 'companyevents';
const String COMPANY_HANDLING            = 'companyhandling';
const String COMPANY_OPENINGHOURS        = 'companyopeninghours';
const String COMPANY_OTHER               = 'companyother';
const String COMPANY_PRODUCT             = 'companyproduct';
const String COMPANY_REGISTRATION_NUMBER = 'companyregistrationnumber';
const String COMPANY_SALESCALLS          = 'companysalescalls';
const String COMPANY_TELEPHONE_NUMBERS   = 'companytelephonenumbers';
const String COMPANY_SELECTOR            = 'companyselector';
const String COMPANY_WEBSITES            = 'companywebsites';
const String CONTACT_INFO                = 'contactinfo';
const String GLOBAL_QUEUE                = 'globalqueue';
const String LOCAL_QUEUE                 = 'localqueue';
const String PHONEBOOTH                  = 'phonebooth';
const String SENDMESSAGE                 = 'sendmessage';

const String COMPANY_ADDRESSES_LIST     = 'company-addresses-list';
const String COMPANY_ALTERNATE_NAMES_LIST = 'company-alternate-names-list';
const String COMPANY_BANKING_INFO_LIST  = 'company-banking-info-list';
const String COMPANY_CUSTOMERTYPE_BODY  = 'company-customertype-body';
const String COMPANY_EMAIL_ADDRESSES_LIST = 'company-email-addresses-list';
const String COMPANY_EVENTS_LIST        = 'company_events_list';
const String COMPANY_HANDLING_LIST      = 'company_handling_list';
const String COMPANY_OPENINGHOURS_LIST  = 'company-opening-hours-list';
const String COMPANY_OTHER_BODY         = 'company-other-body';
const String COMPANY_PRODUCT_BODY       = 'company-product-body';
const String COMPANY_REGISTRATION_NUMBER_LIST = 'company-registration-number-list';
const String COMPANY_SALES_LIST         = 'company-sales-list';
const String COMPANY_SELECTOR_SEARCHBAR = 'company-selector-searchbar';
const String COMPANY_TELEPHONENUMBERS_LIST = 'company-telephonenumbers-list';
const String COMPANY_WEBSITES_LIST      = 'company-websites-list';
const String SENDMESSAGE_SEARCHBOX      = 'sendmessagesearchbox';
const String SENDMESSAGE_SEARCH_RESULT  = 'sendmessagesearchresult';
const String SENDMESSAGE_NAME           = 'sendmessagename';
const String SENDMESSAGE_COMPANY        = 'sendmessagecompany';
const String SENDMESSAGE_PHONE          = 'sendmessagephone';
const String SENDMESSAGE_CELLPHONE      = 'sendmessagecellphone';
const String SENDMESSAGE_LOCALNO        = 'sendmessagelocalno';
const String SENDMESSAGE_TEXT           = 'sendmessagetext';
const String PHONEBOOTH_NUMBERFIELD     = 'phonebooth-numberfield';

