name: ReceptionServer
description: A sample command-line application
dependencies:
  args: any
  openreception_framework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
