#! /bin/bash

cd "$(dirname "$0")/.." || exit 100

if [ ! -d "out" ]; then
   echo "Please run 'make -C $(pwd)'."
   exit 101
fi

if [ -f .pid ]; then
   if [ -d /proc/$(cat .pid) ]; then
      echo "The spawner is already running."
      exit
   fi
fi

echo "Starting the spawner..."

dart spawner/bin/spawner.dart 0</dev/null 1>.output 2>.errors &
pid=$!

if [ -d /proc/${pid} ]; then
   echo "The spawner is running."
   echo ${pid} > .pid
else
   echo "The spawner failed to start properly."

   echo "Standard output:"
   cat .output
   echo

   echo "Standard error:"
   cat .errors
   echo

   exit 103
fi
